{ pkgs, ... }:
with pkgs;
let

  resolvePackage = name: { pkg ? null, isMissing ? false }:
    if pkg != null
    then pkg.meta.name
    else if isMissing == true
    then "cantfind"
    else if builtins.hasAttr name pkgs
    then pkgs.${name}.meta.name
    else throw "Could not find package ${name}";

  packages = {
    "0trace" = { isMissing = true; };
    "aesfix" = { };
    "aeskeyfind" = { };
    "afflib-tools" = { pkg = pkgs.afflib; };
    "afl++" = { pkg = pkgs.aflplusplus; };
    "aircrack-ng" = { };
    "airgeddon" = { };
    "amass" = { };
    "apache-users" = { isMissing = true; };
    "apache2" = { pkg = pkgs.apacheHttpd; };
    "apktool" = { };
    "arachni" = { };
    "armitage" = { isMissing = true; };
    "arping | iputils-arping" = { pkg = pkgs.arping; };
    "asleap" = { };
    "assetfinder" = { isMissing = true; };
    "autopsy" = { isMissing = true; };
    "backdoor-factory" = { isMissing = true; };
    "bed" = { isMissing = true; };
    "beef-xss" = { isMissing = true; };
    "bettercap" = { };
    "binwalk" = { pkg = pkgs.python3Packages.binwalk-full; };
    "bluelog" = { isMissing = true; };
    "blueranger" = { isMissing = true; };
    "bluesnarfer" = { isMissing = true; };
    "bluez" = { };
    "bluez-hcidump" = { isMissing = true; };
    "braa" = { isMissing = true; };
    "btscanner" = { isMissing = true; };
    "bulk-extractor" = { isMissing = true; };
    "bully" = { };
    "burpsuite" = { };
    "bytecode-viewer" = { isMissing = true; };
    "cabextract" = { };
    "cadaver" = { };
    "ccrypt" = { };
    "cdpsnarf" = { };
    "cewl" = { };
    "chirp" = { };
    "chkrootkit" = { };
    "chntpw" = { };
    "cisco-auditing-tool" = { isMissing = true; };
    "cisco-global-exploiter" = { isMissing = true; };
    "cisco-ocs" = { isMissing = true; };
    "cisco-torch" = { isMissing = true; };
    "clamav" = { };
    "clang" = { };
    "cmospwd" = { };
    "commix" = { };
    "cookie-cadger" = { };
    "copy-router-config" = { isMissing = true; };
    "cowpatty" = { };
    "crackle" = { };
    "crackmapexec" = { };
    "creddump7" = { isMissing = true; };
    "crunch" = { };
    "cryptsetup" = { };
    "cryptsetup-initramfs" = { isMissing = true; };
    "cryptsetup-nuke-password" = { isMissing = true; };
    "cutecom" = { };
    "cutycapt" = { isMissing = true; };
    "cymothoa" = { isMissing = true; };
    "darkstat" = { };
    "davtest" = { };
    "dbd" = { isMissing = true; };
    "dc3dd" = { isMissing = true; };
    "dcfldd" = { };
    "ddrescue" = { };
    "default-mysql-server" = { isMissing = true; };
    "defectdojo" = { isMissing = true; };
    "dex2jar" = { };
    "dhcpig" = { isMissing = true; };
    "dirb" = { };
    "dirbuster" = { isMissing = true; };
    "dmitry" = { isMissing = true; };
    "dns2tcp" = { isMissing = true; };
    "dnschef" = { };
    "dnsenum" = { };
    "dnsmap" = { isMissing = true; };
    "dnsrecon" = { };
    "dnstracer" = { };
    "dnswalk" = { isMissing = true; };
    "dotdotpwn" = { isMissing = true; };
    "dradis" = { isMissing = true; };
    "driftnet" = { };
    "dsniff" = { };
    "dumpzilla" = { isMissing = true; };
    "eapmd5pass" = { isMissing = true; };
    "edb-debugger" = { isMissing = true; };
    "enum4linux" = { };
    "enumiax" = { isMissing = true; };
    "ettercap-graphical | ettercap-text-only" = { pkg = pkgs.ettercap; };
    "ewf-tools" = { isMissing = true; };
    "exe2hexbat" = { isMissing = true; };
    "exifprobe" = { };
    "exiv2" = { };
    "exploitdb" = { };
    "ext3grep" = { isMissing = true; };
    "ext4magic" = { };
    "extundelete" = { };
    "eyewitness" = { isMissing = true; };
    "faraday" = { };
    "fcrackzip" = { };
    "fern-wifi-cracker" = { isMissing = true; };
    "ferret-sidejack" = { isMissing = true; };
    "ferret-sidejack" = { };
    "fierce" = { };
    "fiked" = { isMissing = true; };
    "firewalk" = { };
    "firmware-mod-kit" = { isMissing = true; };
    "flashrom" = { };
    "flasm" = { };
    "foremost" = { };
    "forensic-artifacts" = { isMissing = true; };
    "forensics-colorize" = { isMissing = true; };
    "fping" = { };
    "fragrouter" = { isMissing = true; };
    "freeradius-wpe" = { pkg = pkgs.freeradius; };
    "freerdp2-x11" = { isMissing = true; };
    "ftester" = { isMissing = true; };
    "fwbuilder" = { };
    "galleta" = { isMissing = true; };
    "gdb" = { };
    "ghidra" = { };
    "gnuradio" = { };
    "gpart" = { };
    "gparted" = { };
    "gpp-decrypt" = { isMissing = true; };
    "gqrx-sdr" = { pkg = pkgs.gqrx; };
    "gr-air-modes" = { isMissing = true; };
    "gr-iqbal" = { isMissing = true; };
    "gr-osmosdr" = { pkg = gnuradio3_9Packages.osmosdr; };
    "grokevt" = { isMissing = true; };
    "guymager" = { isMissing = true; };
    "gvm" = { isMissing = true; };
    "hackrf" = { };
    "hakrawler" = { };
    "hamster-sidejack" = { isMissing = true; };
    "hash-identifier" = { };
    "hashcat" = { };
    "hashcat-utils" = { };
    "hashdeep" = { };
    "hashid" = { isMissing = true; };
    "hashrat" = { };
    "hb-honeypot" = { isMissing = true; };
    "heartleech" = { isMissing = true; };
    "hexinject" = { isMissing = true; };
    "hostapd-wpe" = { isMissing = true; };
    "hping3" = { pkg = pkgs.hping; };
    "httprint" = { isMissing = true; };
    "httrack" = { };
    "hydra" = { pkg = pkgs.thc-hydra; };
    "hydra-gtk" = { pkg = pkgs.thc-hydra.override (_: { withGUI = true; }); };
    "hyperion" = { isMissing = true; };
    "iaxflood" = { isMissing = true; };
    "ike-scan" = { };
    "impacket-scripts" = { isMissing = true; };
    "inetsim" = { isMissing = true; };
    "inspectrum" = { };
    "intrace" = { isMissing = true; };
    "inviteflood" = { isMissing = true; };
    "iodine" = { };
    "irpas" = { isMissing = true; };
    "isr-evilgrade" = { isMissing = true; };
    "iw" = { };
    "jadx" = { };
    "javasnoop" = { isMissing = true; };
    "jboss-autopwn" = { isMissing = true; };
    "jd-gui" = { };
    "john" = { };
    "johnny" = { };
    "joomscan" = { isMissing = true; };
    "jsql-injection" = { isMissing = true; };
    "kali-autopilot" = { isMissing = true; };
    "kalibrate-rtl" = { };
    "killerbee" = { };
    "kismet" = { };
    "laudanum" = { isMissing = true; };
    "lbd" = { isMissing = true; };
    "legion" = { isMissing = true; };
    "libfindrtp" = { isMissing = true; };
    "libfreefare-bin" = { pkg = pkgs.libfreefare; };
    "libhivex-bin" = { pkg = pkgs.hivex; };
    "libnfc-bin" = { pkg = pkgs.libnfc; };
    "libsmali-java" = { isMissing = true; };
    "lime-forensics" = { };
    "lvm2" = { };
    "lynis" = { };
    "mac-robber" = { isMissing = true; };
    "macchanger" = { };
    "magicrescue" = { isMissing = true; };
    "maltego" = { isMissing = true; };
    "maryam" = { isMissing = true; };
    "maskprocessor" = { isMissing = true; };
    "masscan" = { };
    "md5deep" = { isMissing = true; };
    "mdbtools" = { };
    "mdk3" = { isMissing = true; };
    "mdk4" = { };
    "medusa" = { };
    "memdump" = { isMissing = true; };
    "metacam" = { isMissing = true; };
    "metagoofil" = { isMissing = true; };
    "metasploit-framework" = { pkg = pkgs.metasploit; };
    "mfcuk" = { };
    "mfoc" = { };
    "mfterm" = { isMissing = true; };
    "mimikatz" = { isMissing = true; };
    "minicom" = { };
    "miredo" = { };
    "missidentify" = { isMissing = true; };
    "mitmproxy" = { };
    "msfpc" = { };
    "multimon-ng" = { };
    "myrescue" = { isMissing = true; };
    "nasm" = { };
    "nasty" = { };
    "nbtscan" = { isMissing = true; };
    "ncat" = { isMissing = true; };
    "ncat-w32" = { isMissing = true; };
    "ncrack" = { };
    "netdiscover" = { };
    "netmask" = { };
    "netsniff-ng" = { };
    "nikto" = { };
    "nipper-ng" = { isMissing = true; };
    "nishang" = { isMissing = true; };
    "nmap" = { };
    "oclgausscrack" = { isMissing = true; };
    "ohrwurm" = { isMissing = true; };
    "ollydbg" = { isMissing = true; };
    "onesixtyone" = { };
    "openocd" = { };
    "openvas" = { };
    "ophcrack" = { isMissing = true; };
    "ophcrack-cli" = { isMissing = true; };
    "oscanner" = { isMissing = true; };
    "osrframework" = { isMissing = true; };
    "outguess" = { isMissing = true; };
    "owasp-mantra-ff" = { isMissing = true; };
    "p0f" = { };
    "p7zip-full" = { pkg = pkgs.p7zip; };
    "pack" = { isMissing = true; };
    "pack2" = { isMissing = true; };
    "padbuster" = { };
    "paros" = { isMissing = true; };
    "parted" = { };
    "pasco" = { isMissing = true; };
    "passing-the-hash" = { isMissing = true; };
    "patator" = { pkg = pkgs.python3Packages.patator; };
    "pdf-parser" = { };
    "pdfcrack" = { };
    "pdfid" = { isMissing = true; };
    "peass" = { isMissing = true; };
    "pev" = { };
    "php" = { };
    "php-mysql" = { pkg = phpExtensions.mysqlnd; };
    "pipal" = { isMissing = true; };
    "pixiewps" = { };
    "plaso" = { isMissing = true; };
    "plecost" = { };
    "polenum" = { isMissing = true; };
    "powercat" = { isMissing = true; };
    "powersploit" = { isMissing = true; };
    "protos-sip" = { isMissing = true; };
    "proxmark3" = { };
    "proxychains" = { };
    "proxychains4" = { isMissing = true; };
    "proxychains4" = { };
    "proxytunnel" = { isMissing = true; };
    "pst-utils" = { isMissing = true; };
    "ptunnel" = { isMissing = true; };
    "pwnat" = { };
    "python3-capstone" = { pkg = pkgs.python3Packages.capstone; };
    "python3-dfdatetime" = { isMissing = true; };
    "python3-dfvfs" = { isMissing = true; };
    "python3-dfwinreg" = { isMissing = true; };
    "python3-distorm3" = { pkg = pkgs.python3Packages.distorm3; };
    "qemu" = { };
    "qemu-system-x86" = { isMissing = true; };
    "qemu-user" = { isMissing = true; };
    "qsslcaudit" = { isMissing = true; };
    "radare2" = { };
    "radare2-cutter" = { };
    "rainbowcrack" = { isMissing = true; };
    "rarcrack" = { };
    "rcracki-mt" = { isMissing = true; };
    "reaver" = { pkg = pkgs.reaverwps; };
    "rebind" = { isMissing = true; };
    "recon-ng" = { isMissing = true; };
    "recordmydesktop" = { isMissing = true; };
    "recoverdm" = { isMissing = true; };
    "recoverjpeg" = { };
    "redfang" = { };
    "redsocks" = { };
    "reglookup" = { isMissing = true; };
    "regripper" = { isMissing = true; };
    "rekall-core" = { };
    "rephrase" = { isMissing = true; };
    "responder" = { };
    "rfcat" = { isMissing = true; };
    "rfdump" = { isMissing = true; };
    "rfkill" = { isMissing = true; };
    "rifiuti" = { isMissing = true; };
    "rifiuti2" = { isMissing = true; };
    "rizin-cutter" = { isMissing = true; };
    "rkhunter" = { isMissing = true; };
    "rsakeyfind" = { isMissing = true; };
    "rsmangler" = { isMissing = true; };
    "rtlsdr-scanner" = { isMissing = true; };
    "rtpbreak" = { isMissing = true; };
    "rtpflood" = { isMissing = true; };
    "rtpinsertsound" = { isMissing = true; };
    "rtpmixsound" = { isMissing = true; };
    "rz-ghidra" = { isMissing = true; };
    "safecopy" = { };
    "sakis3g" = { isMissing = true; };
    "samdump2" = { isMissing = true; };
    "sandsifter" = { };
    "sbd" = { isMissing = true; };
    "scalpel" = { isMissing = true; };
    "scrounge-ntfs" = { isMissing = true; };
    "sctpscan" = { isMissing = true; };
    "seclists" = { };
    "secure-socket-funneling-windows-binaries" = { isMissing = true; };
    "sentrypeer" = { isMissing = true; };
    "set" = { isMissing = true; };
    "sfuzz" = { isMissing = true; };
    "shellnoob" = { };
    "shellter" = { isMissing = true; };
    "sidguesser" = { isMissing = true; };
    "siege" = { };
    "siparmyknife" = { isMissing = true; };
    "sipcrack" = { isMissing = true; };
    "sipp" = { };
    "sipsak" = { };
    "sipvicious" = { };
    "skipfish" = { isMissing = true; };
    "sleuthkit" = { };
    "slowhttptest" = { };
    "smali" = { };
    "smbmap" = { };
    "smtp-user-enum" = { isMissing = true; };
    "sniffjoke" = { isMissing = true; };
    "snmpcheck" = { pkg = pkgs.net-snmp; };
    "spectools" = { isMissing = true; };
    "spiderfoot" = { isMissing = true; };
    "spike" = { };
    "spooftooph" = { isMissing = true; };
    "sqldict" = { isMissing = true; };
    "sqlitebrowser" = { };
    "sqlmap" = { };
    "sqlninja" = { isMissing = true; };
    "sqlsus" = { isMissing = true; };
    "ssdeep" = { };
    "ssldump" = { };
    "sslh" = { };
    "sslscan" = { };
    "sslsniff" = { isMissing = true; };
    "sslsplit" = { };
    "sslyze" = { isMissing = true; };
    "statsprocessor" = { isMissing = true; };
    "steghide" = { };
    "stegsnow" = { isMissing = true; };
    "stunnel4" = { isMissing = true; };
    "sucrack" = { isMissing = true; };
    "swaks" = { };
    "t50" = { isMissing = true; };
    "tcpdump" = { };
    "tcpflow" = { };
    "tcpick" = { isMissing = true; };
    "tcpreplay" = { };
    "termineter" = { isMissing = true; };
    "tftpd32" = { isMissing = true; };
    "thc-ipv6" = { };
    "thc-pptp-bruter" = { isMissing = true; };
    "thc-ssl-dos" = { isMissing = true; };
    "theharvester" = { };
    "tiger" = { isMissing = true; };
    "tlssled" = { isMissing = true; };
    "tnscmd10g" = { isMissing = true; };
    "truecrack" = { };
    "twofi" = { isMissing = true; };
    "ubertooth" = { };
    "udptunnel" = { };
    "uhd-host" = { pkg = pkgs.uhd; };
    "uhd-images" = { isMissing = true; };
    "undbx" = { isMissing = true; };
    "unhide" = { isMissing = true; };
    "unicornscan" = { isMissing = true; };
    "uniscan" = { isMissing = true; };
    "unix-privesc-check" = { isMissing = true; };
    "unrar | unar" = { pkg = pkgs.unrar; };
    "upx-ucl" = { isMissing = true; };
    "urlcrazy" = { isMissing = true; };
    "veil" = { isMissing = true; };
    "vinetto" = { isMissing = true; };
    "voiphopper" = { isMissing = true; };
    "volatility" = { };
    "wafw00f" = { };
    "wapiti" = { };
    "watobo" = { isMissing = true; };
    "wce" = { isMissing = true; };
    "webacoo" = { isMissing = true; };
    "webscarab" = { isMissing = true; };
    "webshells" = { isMissing = true; };
    "weevely" = { isMissing = true; };
    "wfuzz" = { };
    "whatweb" = { };
    "wifi-honey" = { isMissing = true; };
    "wifite" = { pkg = pkgs.wifite2; };
    "windows-binaries" = { isMissing = true; };
    "windows-privesc-check" = { isMissing = true; };
    "winregfs" = { isMissing = true; };
    "wireshark" = { };
    "witnessme" = { isMissing = true; };
    "wordlists" = { };
    "wpscan" = { };
    "xmount" = { isMissing = true; };
    "xplico" = { isMissing = true; };
    "xprobe" = { };
    "xsser" = { };
    "yara" = { };
    "yersinia" = { };
    "zaproxy" = { pkg = pkgs.zap; };
  };
in
builtins.mapAttrs resolvePackage packages
